name: TCSkills
version: 1.0.0
main: eu.tamrielcraft.TCSkills.main.Main
author: MarkSlayer456
softdepend: [PlaceholderAPI]
description: A race plugin!

commands:
  race:
    description: Displays all available races
    usage: /<command>
    aliases: [r]
  spell:
    description: base spell command!
    usage: /<command> <command>
    aliases: [s]
  magicregen:
    description: regens magic super fast
    usage: /<command>
    aliases: [mr]    
  favorite:
    description: adds a favorite spell
    usage: /<command> <command>
    aliases: [fav]
  class:
    description: Displays all available classes
    usage: /<command> <command>
    aliases: [c]
  starttc:
    description: start command for the server RP
    usage: /<command> <race> <class>
  skills:
    description: Displays skill tree
    usage: /<command>
  