name: TCSkills
version: 1.0.0
main: eu.tamrielcraft.TCSkills.main.Main
author: MarkSlayer456
softdepend: [PlaceholderAPI]
description: A race plugin!

commands:
  race:
    description: base race command!
    usage: /<command> <command>
    aliases: [r]
  spell:
    description: base spell command!
    usage: /<command> <command>
    aliases: [s]
  magicregen:
    description: regens magic super fast
    usage: /<command>
    aliases: [mr]    
  favorite:
    description: adds a favorite spell
    usage: /<command> <command>
    aliases: [fav]
  class:
    description: base class command
    usage: /<command> <command>
    aliases: [c]